### PR TITLE
add support for python 3.7 and 3.9

### PR DESCRIPTION
**Pull request by romeokienzler**

### CODE REVIEW

**Review by ptitzler — APPROVED** [review]
LGTM

**Comment by ptitzler** [comment]
@romeokienzler does this close Can you please add a description? I'm not sure whether this is supposed to resolve #28 or not.

**Comment by romeokienzler** [comment]
@ptitzler found some other issues - will fix in this PR - will let you know once ready...

**Comment by romeokienzler** [comment]
@ptitzler done 
fixes #28

**Review by ptitzler — APPROVED** [review]
LGTM

**Pull request merged**
